# Loading the Data

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import _pickle as cPickle

In [3]:
df = pd.read_csv("data/train.csv", sep=',')

In [4]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [6]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [7]:
df.shape

(891, 12)

In [8]:
df['Pclass'].unique()

array([3, 1, 2], dtype=int64)

In [9]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [10]:
survived = df[df.Survived == 1]
dead = df[df.Survived == 0]

# Comptage
print(survived.shape)
print(dead.shape)

(342, 12)
(549, 12)


In [11]:
survived

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
..           ...       ...     ...   
875          876         1       3   
879          880         1       1   
880          881         1       2   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ...    ...   
875                   Najib, Miss. Adele Kiamie "Jane"  female  15.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
8        2            347742  11.1333   NaN        S  
9        0            237736  30.0708   NaN        C  
..     ...               ...      ...   ...      ...  
875      0              2667   7.2250   NaN        C  
879      1             11767  83.1583   C50        C  
880      1            230433  26.0000   NaN        S  
887      0            112053  30.0000   B42        S  
889      0            111369  30.0000  C148        C  

[342 rows x 12 columns]

In [12]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [13]:
#Pour savoir les valeurs possible ( group-by )
df['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [14]:
def plot_hist(feature, bins=40):
    plt.rcParams["figure.figsize"] = [16,9]
    x1 = np.array(dead[feature].dropna())
    x2 = np.array(survived[feature].dropna())
    plt.hist([x1, x2], label=["Victime", "Survivant"], bins=bins, color=['r', 'b'])
    plt.legend(loc="upper left")
    plt.title('distribution relative de %s' %feature)
    plt.show()

## Fonction qui remplace les valeurs NaN

In [15]:
#  mediane si quantative
#  mod si qualitative
cabin = df['Cabin'].unique()[5]
def remplaceNanValues(columnName) :
    if columnName == 'Age' :
        x = df[columnName].median()
        print(x)
    elif columnName == 'Cabin' : 
        x= cabin
    else :
        x = df[columnName].unique
        
    for index, row in df.iterrows() :
        if pd.isna(row[columnName]) :
            df.loc[index, columnName] = x

In [16]:
df['Age'].median()

28.0

In [17]:
df['Age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [18]:
remplaceNanValues('Age')

28.0


In [19]:
df['Age'].unique()

array([22.  , 38.  , 26.  , 35.  , 28.  , 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  ,  8.  ,
       19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  , 49.  ,
       29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  , 16.  ,
       25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  , 71.  ,
       37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 , 51.  ,
       55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  , 45.5 ,
       20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  , 60.  ,
       10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  , 70.  ,
       24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [20]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [21]:
remplaceNanValues('Embarked')

In [22]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [23]:
remplaceNanValues('Cabin')

In [24]:
df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

## Transformation des int en string

Transfomer en String les colonnes :
    * Parch
    * Pclass

In [25]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500  C103        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  C103        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500  C103        S

In [26]:
df['Pclass'] = df['Pclass'].astype(str)

In [27]:
df['Parch'] = df['Parch'].apply(str)

In [28]:
def convertColumnTypeToStr(columnName) :    
    for index, row in df.iterrows() :
        original = row[columnName]
        new = str(original)
        row[columnName] = new

In [29]:
#convertColumnTypeToStr('Pclass')

In [30]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass          object
Name            object
Sex             object
Age            float64
SibSp            int64
Parch           object
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

### Choix des Features

In [31]:
features_columns = ['SibSp', 'Fare','Parch']
#to_dummify = ['SibSp','Parch']
to_dummify = ['Parch']
X = df[features_columns]
y = df['Survived']

### Dummification des variables

In [32]:
X.head()

SibSp     Fare Parch
0      1   7.2500     0
1      1  71.2833     0
2      0   7.9250     0
3      1  53.1000     0
4      0   8.0500     0

In [33]:
X = pd.get_dummies(X, columns=to_dummify)

In [34]:
df['SibSp'].unique()

array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [35]:
df['Parch'].unique()

array(['0', '1', '2', '5', '3', '4', '6'], dtype=object)

In [36]:
X.head()

SibSp     Fare  Parch_0  Parch_1  Parch_2  Parch_3  Parch_4  Parch_5  \
0      1   7.2500        1        0        0        0        0        0   
1      1  71.2833        1        0        0        0        0        0   
2      0   7.9250        1        0        0        0        0        0   
3      1  53.1000        1        0        0        0        0        0   
4      0   8.0500        1        0        0        0        0        0   

   Parch_6  
0        0  
1        0  
2        0  
3        0  
4        0

In [37]:
y.head(800)

0      0
1      1
2      1
3      1
4      0
      ..
795    0
796    1
797    1
798    0
799    0
Name: Survived, Length: 800, dtype: int64

# Model

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
def saveModel(model) :
    filename = 'titanic_model.sav'
    cPickle.dump(model, open(filename, 'wb'))

In [40]:
def trainAndScore(model, X, y) :
    list_test_size = [a/20.0 for a in list(range(0,20,1))][1:]
    scores = []
    for ts in list_test_size:
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=ts, random_state=0)
        clf = model.fit(X_train, y_train)
        score = clf.score(X_test, y_test)
        #print("pour ts = " ,ts, "score = ",score)
        scores.append(score)
    print("SCORES : ",scores)
    print("MEAN = ",np.array(scores).mean())
    print("MAX = ",max(scores))
    

# Random Forest

In [41]:
from sklearn.ensemble import RandomForestClassifier

In [42]:
def getTitle(str):
    return str.split(',')[1].split('.')[0].split(' ')[1]

In [43]:
model = RandomForestClassifier(n_estimators = 20)

In [44]:
df = pd.read_csv("data/train.csv", sep=',')

### Replace NaN values

In [45]:
 remplaceNanValues('Cabin')

In [46]:
 remplaceNanValues('Age')

28.0


In [47]:
df['Age'].isna().sum()

0

In [48]:
df['Cabin'].isna().sum()

0

In [49]:
features_columns = ['SibSp', 'Fare','Parch','Pclass', 'Age']
to_dummify = ['Parch', 'Pclass', 'Title']
X = df[features_columns]
y = df['Survived']

In [50]:
X['is_child'] = X['Age'] <=11

c:\python36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [51]:
X['Title'] = df['Name'].apply(lambda x : getTitle(x))
X['Surname'] = df['Name'].apply(lambda x : '(' in x)

c:\python36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
c:\python36\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [52]:
X.head()

SibSp     Fare  Parch  Pclass   Age  is_child Title  Surname
0      1   7.2500      0       3  22.0     False    Mr    False
1      1  71.2833      0       1  38.0     False   Mrs     True
2      0   7.9250      0       3  26.0     False  Miss    False
3      1  53.1000      0       1  35.0     False   Mrs     True
4      0   8.0500      0       3  35.0     False    Mr    False

### Dummify Variables

In [53]:
X = pd.get_dummies(X, columns=to_dummify)
X.head(10)

SibSp     Fare   Age  is_child  Surname  Parch_0  Parch_1  Parch_2  \
0      1   7.2500  22.0     False    False        1        0        0   
1      1  71.2833  38.0     False     True        1        0        0   
2      0   7.9250  26.0     False    False        1        0        0   
3      1  53.1000  35.0     False     True        1        0        0   
4      0   8.0500  35.0     False    False        1        0        0   
5      0   8.4583  28.0     False    False        1        0        0   
6      0  51.8625  54.0     False    False        1        0        0   
7      3  21.0750   2.0      True    False        0        1        0   
8      0  11.1333  27.0     False     True        0        0        1   
9      1  30.0708  14.0     False     True        1        0        0   

   Parch_3  Parch_4  ...  Title_Master  Title_Miss  Title_Mlle  Title_Mme  \
0        0        0  ...             0           0           0          0   
1        0        0  ...             0           0           0          0   
2        0        0  ...             0           1           0          0   
3        0        0  ...             0           0           0          0   
4        0        0  ...             0           0           0          0   
5        0        0  ...             0           0           0          0   
6        0        0  ...             0           0           0          0   
7        0        0  ...             1           0           0          0   
8        0        0  ...             0           0           0          0   
9        0        0  ...             0           0           0          0   

   Title_Mr  Title_Mrs  Title_Ms  Title_Rev  Title_Sir  Title_the  
0         1          0         0          0          0          0  
1         0          1         0          0          0          0  
2         0          0         0          0          0          0  
3         0          1         0          0          0          0  
4         1          0         0          0          0          0  
5         1          0         0          0          0          0  
6         1          0         0          0          0          0  
7         0          0         0          0          0          0  
8         0          1         0          0          0          0  
9         0          1         0          0          0          0  

[10 rows x 32 columns]

## Using Grid Search CV to find the best Params (Best Way)

In [54]:
from sklearn.model_selection import GridSearchCV

rfc = RandomForestClassifier(n_jobs=-1,max_features= 'sqrt' ,n_estimators=50, oob_score = True) 

param_grid = { 
    'n_estimators': [150, 200],
    'max_depth' : [2, 40],
    'min_samples_split': [3, 20],
    'max_features': ['auto', 'sqrt', 'log2']
}

CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
CV_rfc.fit(X, y)
print(CV_rfc.best_params_)

{'max_depth': 40, 'max_features': 'auto', 'min_samples_split': 20, 'n_estimators': 150}


In [55]:
model = RandomForestClassifier(n_estimators = 200, max_depth= 40 , min_samples_split = 20, max_features='log2')
trainAndScore(model, X, y)

SCORES :  [0.8666666666666667, 0.8222222222222222, 0.7985074626865671, 0.8212290502793296, 0.8116591928251121, 0.8059701492537313, 0.8076923076923077, 0.7983193277310925, 0.8029925187032418, 0.8116591928251121, 0.8167006109979633, 0.8168224299065421, 0.8017241379310345, 0.7948717948717948, 0.7937219730941704, 0.7699859747545582, 0.7612137203166227, 0.7793017456359103, 0.7804014167650531]
MEAN =  0.803245362903107
MAX =  0.8666666666666667


In [56]:
model = RandomForestClassifier(n_estimators = 200, max_depth= 40 , min_samples_split = 20, max_features='sqrt')
trainAndScore(model, X, y)

SCORES :  [0.8666666666666667, 0.8444444444444444, 0.7985074626865671, 0.8100558659217877, 0.8116591928251121, 0.8097014925373134, 0.8012820512820513, 0.8011204481792717, 0.8054862842892768, 0.8116591928251121, 0.8126272912423625, 0.8168224299065421, 0.8086206896551724, 0.8012820512820513, 0.7982062780269058, 0.7573632538569425, 0.7638522427440633, 0.7830423940149626, 0.7839433293978748]
MEAN =  0.8045443716728675
MAX =  0.8666666666666667


## We can search the feature manually with a function

### Grid Search CV remains Better

In [ ]:
trainAndScore(model, X, y)

In [ ]:
def findBestParams(p,n,pas):
    for i in range (p,n,pas):
        model = RandomForestClassifier(n_estimators = i)
        print('----------------- ',i,'-th RandomForestClassifier --------------')
        trainAndScore(model, X, y)

In [ ]:
findBestParams(50,500,50)

In [ ]:
findBestParams(10,50,5)

In [ ]:
findBestParams(1,11,1)

### Adding more params to our Random Forest Classifier

* min_samples_split
* max_depth

In [ ]:
def findBestParams(p,n,pas, mdepth, msplit):
    for i in range (p,n,pas):
        model = RandomForestClassifier(n_estimators = i, max_depth= mdepth , min_samples_split = msplit)
        print('----------------- ',i,'-th RandomForestClassifier --------------')
        trainAndScore(model, X, y)

In [ ]:
def run(p,n,pas):
    for i in range(2,8):
        print('------ Min Samples Split = ',i,'-----------------------')
        for j in range (7,20):
            print('------ Max Depth = ',j,'-----------------------')
            findBestParams(p,n,pas, j, i)

In [ ]:
run(1,11,1)